- .codeqlmanifest.json
`.codeqlmanifest.json` can chain to a `.codeqlmanifest.json` in a subdirectory.
This way you don't need to copy-paste the contents of the manifest from the codeql/codeql-queries subdmodule, making it easier to stay in sync with its content.
> chain to the codeql submodule's manifest instead of replicating it

- codeql/windows-drivers/suites/windows_driver_mustfix.qls
The "Likely Bugs/Memory Management/UninitializedLocal.ql" query is showing too many false positives at the moment, and so we are moving it from must-fix to recommended.
> Remove uninitialized local check from must-fix due to high noise.

- .github/workflows/build-codeql.yaml
This PR creates a GitHub action that builds all CodeQL queries in the windows_driver_recommended.qls suite, which covers all queries we are currently officially supporting to be run as part of certification.
This action attempts to clone this repo and its submodules, fetch v2.5.0 of the CodeQL CLI, and then run codeql-compile on the aforementioned suite.
> Add build action for the CodeQL queries in the recommended suite.

- .gitignore
- codeql/windows-drivers/queries/Likely Bugs/Boundary Violations/InformationLeakBoundaries.qll
- codeql/windows-drivers/queries/Likely Bugs/Boundary Violations/PaddingByteInformationDisclosure.ql
- codeql/windows-drivers/queries/Likely Bugs/Boundary Violations/PaddingByteInformationDisclosureBadCode.c
- codeql/windows-drivers/queries/Likely Bugs/Boundary Violations/PaddingByteInformationDisclosureGoodCode.c
- codeql/windows-drivers/queries/Likely Bugs/Conversion/BadOverflowGuard.ql
- codeql/windows-drivers/queries/Likely Bugs/Conversion/BadOverflowGuardBadCode.c
- codeql/windows-drivers/queries/Likely Bugs/Conversion/BadOverflowGuardGoodCode.c
- codeql/windows-drivers/queries/Likely Bugs/Conversion/InfiniteLoop.ql
- codeql/windows-drivers/queries/Likely Bugs/Conversion/InfiniteLoopBadCode.c
- codeql/windows-drivers/queries/Likely Bugs/Conversion/InfiniteLoopGoodCode.c
- codeql/windows-drivers/queries/Likely Bugs/Memory Management/UseAfterFree/UseAfterFree_bad.c
- codeql/windows-drivers/queries/Likely Bugs/Memory Management/UseAfterFree/UseAfterFree_good.c
- codeql/windows-drivers/queries/Likely Bugs/UninitializedPtrField.ql
- codeql/windows-drivers/queries/Likely Bugs/UninitializedPtrFieldBadCode.c
- codeql/windows-drivers/queries/Likely Bugs/UninitializedPtrFieldGoodCode.c
- codeql/windows-drivers/queries/Security/Crytpography/HardcodedIVCNG.ql
- codeql/windows-drivers/queries/microsoft/code/cpp/commons/Literals.qll
- codeql/windows-drivers/queries/microsoft/code/cpp/commons/MemoryAllocation.qll
Add copyright headers to the recently added recommended queries and libraries.
> Add missing copyright headers.

- .github/workflows/build-codeql.yaml
The current workflow only builds the queries we own.  This update changes the workflow to build the entire recommended suite, including queries from the main repo, to help catch any issues where upstream changes break us.
> Build driver recommended suite

- codeql/windows-drivers/suites/windows_driver_recommended.qls
Our query suites today are set up so that "recommended" is a superset of "must-fix".  However, the suite itself manually duplicates the must-fix queries rather than import the existing suite, which can lead to issues where the suites drift out of sync unintentionally.
This change updates the recommended suite to import the must-fix suite instead of duplicating it, which resolves this issue and also makes it more clear which queries are must-fix versus recommended.
> Refactor suites to import rather than duplicate

- src/drivers/wdm/libraries/WdmDrivers.qll
The WDM library was detecting if a function was a WDM callback routine by checking if:
- The function typedef matched a set of WDM typedef names, and
- The function definition was in a file that imported wdm.h.
Thus in the case where a function was declared in the same file as its definition, and not in a separate header file that included wdm.h, the function would be incorrectly marked as not a WDM callback.
This change updates the logic so that the detection is based on if the typedef itself is defined in wdm.h.
> Fix detection of WDM typedefs

- codeql/windows-drivers/queries/Security/CWE/CWE-704/WcharCharConversion.cpp
- codeql/windows-drivers/queries/Security/CWE/CWE-704/WcharCharConversionLimited.qhelp
- codeql/windows-drivers/queries/Security/CWE/CWE-704/WcharCharConversionLimited.ql
- codeql/windows-drivers/queries/suites/windows_driver_mustfix.qls
- codeql/windows-drivers/queries/suites/windows_driver_recommended.qls
Since the original query is GitHub published, and the PUCHAR false positive pattern seems to be specific to driver writers, we are adding a new query to address the FPs, while keeping the original query under the `recommended` category.
> Fixing a FP pattern for PUCHAR casting

- .github/workflows/build-codeql.yaml
- README.md
- codeql-workspace.yml
- src/codeql-pack.lock.yml
- src/qlpack.yml
- src/suites/ported_driver_ca_checks.qls
- src/suites/windows_driver_mustfix.qls
- src/suites/windows_driver_recommended.qls
Updates CodeQL version from 2.6.3. to 2.11.5
- Readme - adds in new procedure for users to run analysis & links to new CodeQL CLI version
- Removes codeql-queries submodule
- Package version *not* updated since there is no substantial change to it
- Unit Tests *not* run due to test process being in active development
- Commands `codeql database create` and `codeql database analyze` have completed successfully
> Updates repo to use CodeQL v2.11.5

- .github/workflows/build-codeql.yaml
- src/codeql-pack.lock.yml
- src/qlpack.yml
The recent update to CLI version 2.11.5 did not update the associated CodeQL core library/query packs.  To ensure we have good alignment between the CLI and the libraries, this change updates our pack dependencies.  Users should re-run "codeql pack install" from the src directory after this change.
The dependency version was taken from these files: 
https://github.com/github/codeql/blob/codeql-cli/v2.11.5/cpp/ql/src/qlpack.yml
https://github.com/github/codeql/blob/codeql-cli/v2.11.5/cpp/ql/lib/qlpack.yml
> Update CodeQL pack references to match CLI 2.11.5.

- src/microsoft/Security/CWE/CWE-704/WcharCharConversionLimited.ql
Quick fix to a typo in WcharCharConversionLimited.ql.
Fixes #46.
> Fix typo in WcharCharConversionLimited.ql

- src/drivers/test/build_create_analyze_test.cmd
- src/drivers/wdm/queries/KeWaitLocal/KeWaitLocal.sarif
KeWaitLocal had an outdated test baseline (due to changes in its metadata, but no changes to the query itself) and DefaultPoolTag had a typo in the test script that resulted in its test failing to run.  This change fixes both those issues and returns the test baseline to a clean state.
> Fix two benign test issues that were causing noise.

- src/drivers/general/queries/WdkDeprecatedApis/WdkDeprecatedApis.sarif
- src/drivers/general/queries/WdkDeprecatedApis/driver_snippet.c
- src/drivers/general/queries/WdkDeprecatedApis/wdk-deprecated-api.ql
This change updates the WdkDeprecatedApis query to correctly report usages of deprecated APIs when they are in macro form.  Depending on the compilation environment, Windows may redefine i.e. ExAllocatePoolTag to ExAllocatePool.  Previously, this query would then report a call to ExAllocatePool, which, while technically correct, was confusing to the end user.  The error message will now report the macro call actually present in the code.
> Improve messaging for WdkDeprecatedApis check.

- src/drivers/general/DriverAlertSuppression.ql
- src/drivers/general/queries/ExtendedDeprecatedApis/ExtendedDeprecatedApis.sarif
- src/drivers/general/queries/ExtendedDeprecatedApis/driver_snippet.c
- src/drivers/libraries/Suppression.qll
This PR adds a library and alert-suppression query for using the existing Code Analysis suppression annotations for our queries that were ported from CA.  To run the query, it should be run as part of a suite with other rules and the results output to SARIF; the SARIF will then be annotated to indicate the issue was suppressed at the source level.  
There are a few cases related to the semantics of pragma suppression that are not yet implemented, but are called out as bugs in the test cases and to-dos in the suppression library.
As this is not a formal query, it cannot use our standard test infrastructure (attempting to run the query on its own will result in an empty SARIF file).  Instead, test cases have been added to the ExtendedDeprecatedAPIs test.  When testing this query, you should …
> Create a library and query for converting Code Analysis-style suppressions to CodeQL suppressions.

- src/drivers/general/DriverAlertSuppression.ql
- src/drivers/general/queries/ExtendedDeprecatedApis/ExtendedDeprecatedApis.sarif
- src/drivers/general/queries/ExtendedDeprecatedApis/driver_snippet.c
- src/drivers/libraries/Suppression.qll
- [N/A] The version number on changed queries has been increased via the `@version` comment in the file header.
- [N/A] A .qhelp file has been added for any new queries or updated if changes have been made to an existing query.
Updates our suppression library to cover the following cases:
- Multiple rules suppressed in a single pragma
- Multiple pragmas listed consecutively to apply to a single line
- Disable pragmas are honored outside of push/pop segments
Also adds more comments to the suppression library/query and the associated test code.
Resolves #70.
> Extend suppression library to more cases and cleanup

- src/drivers/general/DriverAlertSuppression.ql
- src/drivers/general/queries/ExtendedDeprecatedApis/ExtendedDeprecatedApis.sarif
- src/drivers/general/queries/ExtendedDeprecatedApis/driver_snippet.c
- src/drivers/libraries/Suppression.qll
* Add support for stacked suppressions + empty lines between
* Allow multiple rules in one suppression
* Use cache + nomagic to improve perf.
* Missed updating a line in test code
* Support disable outside of push/pop
* Fix support for comments in suppression pragmas
* Clean up test code and add more comments
* Clarify some wording
> Extend suppression library to more cases and cleanup (#71)

- src/drivers/general/queries/IrqlTooHigh/IrqlTooHigh.ql
- src/drivers/general/queries/IrqlTooHigh/IrqlTooHigh.sarif
- src/drivers/general/queries/IrqlTooLow/IrqlTooLow.ql
- src/drivers/general/queries/IrqlTooLow/IrqlTooLow.sarif
- src/drivers/general/queries/RoleTypeCorrectlyUsed/RoleTypeCorrectlyUsed.ql
- src/drivers/general/queries/RoleTypeCorrectlyUsed/RoleTypeCorrectlyUsed.sarif
- src/drivers/libraries/Suppression.qll
The suppression library needed to be updated to use our new query ID layouts (from release preparation) and add missing entries.  This also fixes the opaque IDs used for a few queries that didn't match the CA equivalents (or had no CA equivalent in one case.)
- [N/A] The version number on changed queries has been increased via the `@version` comment in the file header.
> Update suppression library to use new query IDs.

- src/drivers/general/queries/ExtendedDeprecatedApis/ExtendedDeprecatedApis.ql
> Add APIs to ExtendedDeprecatedApis for Codeql port of c28727

- src/drivers/general/queries/IrqlFunctionNotAnnotated/IrqlFunctionNotAnnotated.qhelp
- src/drivers/general/queries/IrqlFunctionNotAnnotated/IrqlFunctionNotAnnotated.ql
- src/drivers/general/queries/IrqlFunctionNotAnnotated/IrqlFunctionNotAnnotated.sarif
- src/drivers/general/queries/IrqlFunctionNotAnnotated/driver_snippet.c
> IrqlFunctionNotAnnotated: codeql port of c28167

- src/drivers/general/queries/IrqlLoweredImproperly/IrqlLoweredImproperly.qhelp
- src/drivers/general/queries/IrqlLoweredImproperly/IrqlLoweredImproperly.ql
- src/drivers/general/queries/IrqlLoweredImproperly/IrqlLoweredImproperly.sarif
- src/drivers/general/queries/IrqlLoweredImproperly/driver_snippet.c
> IrqlLoweredImproperly: Codeql port of c28141

- src/drivers/general/queries/IrqlCancelRoutine/IrqlCancelRoutine.qhelp
- src/drivers/general/queries/IrqlCancelRoutine/IrqlCancelRoutine.ql
- src/drivers/general/queries/IrqlCancelRoutine/IrqlCancelRoutine.sarif
- src/drivers/general/queries/IrqlCancelRoutine/driver_snippet.c
- src/drivers/test/WDMTestTemplate/driver/fail_driver1.c
- src/drivers/test/WDMTestTemplate/driver/fail_driver1.h
> IrqlCancelRoutine: CodeQL port of c28144

- src/drivers/general/queries/IrqlInconsistentWithRequired/IrqlInconsistentWithRequired.qhelp
- src/drivers/general/queries/IrqlInconsistentWithRequired/IrqlInconsistentWithRequired.ql
- src/drivers/general/queries/IrqlInconsistentWithRequired/IrqlInconsistentWithRequired.sarif
- src/drivers/general/queries/IrqlInconsistentWithRequired/driver_snippet.c
> IrqlInconsistentWithRequired: CodeQL port of C28166

- src/drivers/general/queries/InvalidFunctionClassTypedef/InvalidFunctionClassTypedef.qhelp
- src/drivers/general/queries/InvalidFunctionClassTypedef/InvalidFunctionClassTypedef.ql
- src/drivers/general/queries/InvalidFunctionClassTypedef/InvalidFunctionClassTypedef.sarif
- src/drivers/general/queries/InvalidFunctionClassTypedef/driver_snippet.c
> InvalidFunctionClassTypedef: Codeql port of c28268

- src/drivers/general/queries/StrictTypeMatch/StrictTypeMatch.qhelp
- src/drivers/general/queries/StrictTypeMatch/StrictTypeMatch.ql
- src/drivers/general/queries/StrictTypeMatch/StrictTypeMatch.sarif
- src/drivers/general/queries/StrictTypeMatch/driver_snippet.c
> StrictTypeMatch: Codeql port of c28139

- src/drivers/general/queries/MultipleFunctionClassAnnotations/MultipleFunctionClassAnnotations.qhelp
- src/drivers/general/queries/MultipleFunctionClassAnnotations/MultipleFunctionClassAnnotations.ql
- src/drivers/general/queries/MultipleFunctionClassAnnotations/MultipleFunctionClassAnnotations.sarif
- src/drivers/general/queries/MultipleFunctionClassAnnotations/driver_snippet.c
> MultipleFunctionClassAnnotations: Port of C28177

- .github/workflows/build-codeql.yaml
- .github/workflows/publish.yml
- src/drivers/test/build_create_analyze_test.py
> Actions azure file storage fix

- src/qlpack.yml
- src/windows-driver-suites/mustfix.qls
- src/windows-driver-suites/recommended.qls
> update mustfix and recommended suites

- .github/workflows/publish.yml
> update publish to allow prerelease versions
